import coreapi
import coreschema
from rest_framework.schemas import AutoSchema


token_field = coreapi.Field(
    name="Authorization",
    required=False,
    location="header",
    schema=coreschema.String(),
    description="格式：JWT 值",
)

TokenSchema = AutoSchema([
    token_field
])

AddUserSchema = AutoSchema([
    coreapi.Field("account",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户账号", ),
    coreapi.Field("password",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户密码", ),
    coreapi.Field("username",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户名", ),
    coreapi.Field("telephone",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="联系电话", ),
    coreapi.Field("gender",
                  required=False,
                  location="form",
                  schema=coreschema.Integer(),
                  description="性别", ),
    coreapi.Field("is_active",
                  required=False,
                  location="form",
                  schema=coreschema.Integer(),
                  description="是否冻结", ),
    coreapi.Field("userNo",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户工号", ),
    coreapi.Field("address",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="现居住地", ),
    coreapi.Field("detail",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="描述信息", ),
    coreapi.Field("avatar",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户头像", ),
])

UpdateUserSchema = AutoSchema([
    coreapi.Field("id",
                  required=True,
                  location="form",
                  schema=coreschema.Integer(),
                  description="用户id", ),
    coreapi.Field("username",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户名", ),
    coreapi.Field("telephone",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="联系电话", ),
    coreapi.Field("gender",
                  required=False,
                  location="form",
                  schema=coreschema.Integer(),
                  description="性别", ),
    coreapi.Field("is_active",
                  required=False,
                  location="form",
                  schema=coreschema.Integer(),
                  description="是否冻结", ),
    coreapi.Field("address",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="现居住地", ),
    coreapi.Field("detail",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="描述信息", ),
    coreapi.Field("avatar",
                  required=False,
                  location="form",
                  schema=coreschema.String(),
                  description="用户头像", ),
])

DeleteUserSchema = AutoSchema([
    coreapi.Field("id",
                  required=True,
                  location="form",
                  schema=coreschema.Integer(),
                  description="用户id", ),
])
