# Generated by Django 2.2.6 on 2019-10-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, unique=True, verbose_name='用户账号')),
                ('userNo', models.CharField(max_length=255, unique=True, verbose_name='用户工号')),
                ('telephone', models.CharField(max_length=11, unique=True, verbose_name='用户手机号')),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'secret'), (4, 'unknown')], verbose_name='用户性别')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户描述')),
                ('avatar', models.ImageField(upload_to='upload/user/%Y/&m', verbose_name='用户头像')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
