# Generated by Django 2.2.6 on 2019-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191024_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/user/%Y/&m', verbose_name='用户头像'),
        ),
    ]
