# Generated by Django 2.2.6 on 2019-10-23 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='视频添加时间')),
                ('name', models.CharField(max_length=255, verbose_name='视频名称')),
                ('detail', models.CharField(max_length=255, verbose_name='视频描述')),
                ('address', models.CharField(max_length=255, verbose_name='视频地址')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '视频监控表',
            },
        ),
    ]
