# Generated by Django 2.2.6 on 2019-10-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='视频地址'),
        ),
    ]
