# Generated by Django 2.2.6 on 2019-10-25 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(verbose_name='告警级别添加时间')),
                ('name', models.CharField(max_length=255, verbose_name='告警级别名称')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警级别说明')),
            ],
            options={
                'verbose_name': '告警级别表',
            },
        ),
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警类型添加时间')),
                ('name', models.CharField(max_length=255, verbose_name='告警类型名称')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警类型说明')),
            ],
            options={
                'verbose_name': '告警类型表',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警添加时间')),
                ('device', models.CharField(max_length=255, verbose_name='告警设备')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警内容')),
                ('status', models.IntegerField(choices=[(1, '待处理'), (2, '待审核'), (3, '审核通过'), (4, '审核不通过')], default=1, verbose_name='告警状态')),
                ('deal_user', models.IntegerField(verbose_name='告警处理人')),
                ('deal_time', models.DateTimeField(blank=True, null=True, verbose_name='告警处理时间')),
                ('deal_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警处理说明')),
                ('audit_user', models.IntegerField(verbose_name='告警审核人')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='告警审核时间')),
                ('audit_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警审核说明')),
                ('alarm_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.AlarmLevel', verbose_name='告警级别')),
                ('alarm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.AlarmType', verbose_name='告警类型')),
            ],
            options={
                'verbose_name': '告警表',
            },
        ),
    ]
