# Generated by Django 2.2.6 on 2019-10-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_auto_20191025_1717'),
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm_scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scene.Scene', verbose_name='所属场景'),
        ),
        migrations.AlterField(
            model_name='alarmlevel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='告警级别名称'),
        ),
        migrations.AlterField(
            model_name='alarmtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='告警类型名称'),
        ),
    ]
