# Generated by Django 2.2.6 on 2019-10-23 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='日志添加时间')),
                ('content', models.CharField(max_length=500, verbose_name='日志内容')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='操作用户')),
                ('log_module', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '日志信息表',
            },
        ),
    ]
