# Generated by Django 2.2.6 on 2019-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='scene',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='所属场景'),
        ),
    ]
