# Generated by Django 2.2.6 on 2019-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessControls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AlterField(
            model_name='accesses',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请结束时间'),
        ),
        migrations.AlterField(
            model_name='accesses',
            name='status',
            field=models.IntegerField(choices=[(1, '待审核'), (2, '已通过'), (3, '已拒绝')], default=1, verbose_name='申请状态'),
        ),
    ]
