# Generated by Django 2.2.6 on 2019-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessControls', '0002_auto_20191023_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='approval_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='审批人'),
        ),
    ]
