# Generated by Django 2.2.6 on 2019-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessControls', '0003_auto_20191023_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请开始时间'),
        ),
    ]
