# Generated by Django 2.2.6 on 2019-10-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessControls', '0005_auto_20191029_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesses',
            old_name='user_id',
            new_name='username',
        ),
    ]
