# Generated by Django 2.2.6 on 2019-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessControls', '0006_auto_20191029_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='approval_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='审批人'),
        ),
    ]
