# Generated by Django 2.2.6 on 2019-11-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessControls', '0007_auto_20191029_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesses',
            options={'permissions': (('access_view', '门禁信息查看'), ('add_access', '门禁信息申请'), ('update_access', '门禁信息处理')), 'verbose_name': '门禁审批表'},
        ),
    ]
