# Generated by Django 2.2.6 on 2019-10-25 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='场景添加时间')),
                ('name', models.CharField(max_length=255, verbose_name='场景名称')),
                ('code', models.CharField(max_length=255, verbose_name='场景识别码')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='场景状态')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='场景优先级')),
            ],
            options={
                'verbose_name': '场景表',
            },
        ),
    ]
