# Generated by Django 2.2.6 on 2019-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='场景名称'),
        ),
    ]
