# Generated by Django 2.2.6 on 2019-10-29 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_alarmlamp_alertor_beam_co2_display_fan_flame_humidity_invade_light_methane_pm25_pump_smoke_temperatu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlocking',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 33, 38, 366537), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 33, 38, 366537), verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 33, 38, 368529), verbose_name='入侵检测更新时间'),
        ),
    ]
