# Generated by Django 2.2.6 on 2019-10-29 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0004_auto_20191029_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmlamp',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 36, 51, 878877), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 36, 51, 879875), verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 36, 51, 881869), verbose_name='入侵检测更新时间'),
        ),
        migrations.AlterField(
            model_name='unlocking',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开锁记录更新时间'),
        ),
    ]
