# Generated by Django 2.2.6 on 2019-10-29 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_auto_20191029_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmlamp',
            name='name',
            field=models.CharField(default='报警灯', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='alertor',
            name='name',
            field=models.CharField(default='报警器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='beam',
            name='name',
            field=models.CharField(default='光照强度传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='co2',
            name='name',
            field=models.CharField(default='Co2传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='display',
            name='name',
            field=models.CharField(default='LCD显示屏', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='fan',
            name='name',
            field=models.CharField(default='风扇传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='flame',
            name='name',
            field=models.CharField(default='火光传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='name',
            field=models.CharField(default='湿度传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='invade',
            name='name',
            field=models.CharField(default='入侵检测', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='light',
            name='name',
            field=models.CharField(default='灯光传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='methane',
            name='name',
            field=models.CharField(default='甲烷传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='pm25',
            name='name',
            field=models.CharField(default='PM2.5传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='pump',
            name='name',
            field=models.CharField(default='水泵传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='smoke',
            name='name',
            field=models.CharField(default='烟雾传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='name',
            field=models.CharField(default='温度传感器', max_length=255, verbose_name='表名'),
        ),
        migrations.AddField(
            model_name='unlocking',
            name='name',
            field=models.CharField(default='开锁记录', max_length=255, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 8, 21, 543208), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 8, 21, 544182), verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='入侵检测更新时间'),
        ),
    ]
