# Generated by Django 2.2.6 on 2019-10-29 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0006_auto_20191029_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='password',
            field=models.CharField(default=123456, max_length=255, verbose_name='网关密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 40, 56, 426731), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 40, 56, 427728), verbose_name='报警器更新时间'),
        ),
    ]
