# Generated by Django 2.2.6 on 2019-10-29 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0007_auto_20191029_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmlamp',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='报警灯状态'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='insert_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='报警器状态'),
        ),
        migrations.AlterField(
            model_name='beam',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='beam',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='传感器状态'),
        ),
        migrations.AlterField(
            model_name='co2',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='co2',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='传感器状态'),
        ),
        migrations.AlterField(
            model_name='display',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='display',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='风扇状态'),
        ),
        migrations.AlterField(
            model_name='flame',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='flame',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='火光状态'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='传感器状态'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='入侵状态'),
        ),
        migrations.AlterField(
            model_name='light',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='light',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='灯光状态'),
        ),
        migrations.AlterField(
            model_name='methane',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='methane',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='甲烷状态'),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='pm25状态'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='水泵状态'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], default=1, verbose_name='场景状态'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='烟雾状态'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='online',
            field=models.IntegerField(choices=[(1, '在线'), (0, '离线')], verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='传感器状态'),
        ),
        migrations.AlterField(
            model_name='unlocking',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], verbose_name='开锁状态'),
        ),
    ]
